### ISSUE TITLE
execute Ocean Marketplace transaction through button extension

### ISSUE THREAD

**Issue by smejak** [AlgoveraAI/jupyterlab_extensions#2]
Currently the extension has two available buttons, one for connecting  a Metamask wallet and another for sending a predefined transaction.
A good next step would be to add a button that executes a predefined Ocean Marketplace transaction (e.g. buying a datatoken from the generative art pool)

**Comment by nollied** [comment]
should we close this? it seems like we want to avoid OCEAN right?

**Comment by smejak** [comment]
Yeah this is no longer relevant, the ocean transaction takes place as a function call in the cell.
